name: Build and upload slides

on:
  # # every midnight
  # schedule:
  #   - cron:  '0 0 * * *'
  # manual trigger
  workflow_dispatch:
  # push
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Install quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.36/quarto-1.6.36-linux-amd64.deb
          sudo dpkg -i quarto-1.6.36-linux-amd64.deb

      - name: Create slides
        run: |
          quarto render slides.qmd

      - name: Convert revealjs slides to pdf
        run: |
          docker run --user root --rm -t -v `pwd`:/slides astefanutti/decktape slides.html slides.pdf

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: Slides
          path: |
            **/*.pdf
            **/*.html
            slides_files/**
            media/**
          if-no-files-found: error
